test:
  script:
    - make rebuild_services rebuild_catalinker docker_compose_up test
  only:
    - develop
  stage: test

build:
  script:
    - LSDEVMODE=ci LSEXTPATH=$(pwd) make rebuild_services rebuild_catalinker login push
  only:
    - tags
  stage: build
  tags:
    - build
