---
version: '3'

services:

  services:
    build:
      context: "${LSEXTPATH}/redef/services"
      dockerfile: Dockerfile
    depends_on:
      - fuseki
      - koha
    environment:
      KOHA_MYSQL_USER: "${KOHA_ADMINUSER:-admin}"
      KOHA_MYSQL_PASS: "${KOHA_ADMINPASS:-secret}"
      KOHA_MYSQL_DB: "koha_${KOHA_INSTANCE:-name}"
      KOHA_API_PASS_ENCRYPTED: "$$2a$$08$$7WnfE3Fyh5W0C28Xp2SWH.NfgqLEZzw9oZI4qZ3MHf.lQS8yvv6hC"

  catalinker:
    build:
      context: "${LSEXTPATH:-..}/redef/catalinker"
      dockerfile: Dockerfile

  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

