---
version: '2.1'

services:
  koha:
    logging:
      driver: "journald"

  koha_mysql:
    command:
      - mysqld
      - "--datadir=/var/lib/mysql"
      - "--user=mysql"
      - "--max_allowed_packet=64M"
      - "--wait_timeout=6000"
      - "--bind-address=0.0.0.0"
      - "--innodb-buffer-pool-size=16G"
      - "--max-connections=500"
      - "--innodb-flush-method=O_DIRECT"
      - "--skip-name-resolve"
    logging:
      driver: "journald"

  services:
    logging:
      driver: "journald"

  catalinker:
    logging:
      driver: "journald"

  patron_client:
    logging:
      driver: "journald"

  rfidhub:
    container_name: rfidhub
    image: "digibib/rfidhub2:5cc223d57472232557fbcc608c45f7ac22372fb9"
    networks:
      - backend
    depends_on:
      - sip_proxy
    ports:
      - "8899:8899"
    environment:
      SIP_SERVER: sip_proxy:9999
      TCP_PORT: 6006
      SIP_USER: rfidhub
      SIP_PASS: "${SIP_AUTOPASS:-autopass}"
    logging:
      driver: "journald"

  smtp:
    environment:
      FORWARD_SMTP: "${FORWARD_SMTP}"
    logging:
      driver: "journald"

  sms:
    environment:
      FORWARD_SMS: "${FORWARD_SMS}"
    logging:
      driver: "journald"

  elasticsearch:
    logging:
      driver: "journald"
    environment:
      - cluster.name=deichman-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  fuseki:
    logging:
      driver: "journald"

  tagvision_sip_proxy:
    container_name: tagvision_sip_proxy
    image: "digibib/sip2proxy:3891478ccc5dc17abd16004b6780885774cd6d44"
    networks:
      - backend
    restart: always
    ports:
      - "6002:9999"
    command:
      - "/sip2proxy"
      - "-from=:9999"
      - "-to=xkoha:${SIP_PORT:-6001}"
      - "-log-messages=true"
      - "-strip-barcode=true"
      - "-extend-barcode=true"
      - "-ensure-branch=true"
      - "-gelf=udp://10.172.2.16:12201"
      - "-no-alert-if-same-branch=true"
    hostname: sputnik/sip/tagvision
    logging:
      driver: "journald"

  bibliotheca_sip_proxy:
    container_name: bibliotheca_sip_proxy
    image: "digibib/sip2proxy:3891478ccc5dc17abd16004b6780885774cd6d44"
    networks:
      - backend
    restart: always
    ports:
      - "6003:9999"
    command:
      - "/sip2proxy"
      - "-from=:9999"
      - "-to=xkoha:${SIP_PORT:-6001}"
      - "-strip-barcode=true"
      - "-log-messages=true"
      - "-gelf=udp://10.172.2.16:12201"
    hostname: sputnik/sip/axiell
    logging:
      driver: "journald"

  sip_proxy:
    container_name: sip_proxy
    image: "digibib/sip2proxy:3891478ccc5dc17abd16004b6780885774cd6d44"
    command:
      - "/sip2proxy"
      - "-from=:9999"
      - "-to=xkoha:${SIP_PORT:-6001}"
      - "-log-messages=true"
      - "-strip-barcode=true"
      - "-ensure-branch=true"
      - "-gelf=udp://10.172.2.16:12201"
      - "-extended-id=false"
    hostname: sputnik/sip
    logging:
      driver: "journald"

  overview:
    logging:
      driver: "journald"

  search_metrics:
    container_name: search_metrics
    image: digibib/search_metrics:0ef9ab2b5569df60b11a4c7f1f40c4ec88f1c730
    networks:
      - backend
    extra_hosts:
      - "metrics:10.172.2.97"
      - "sok.deichman.no:10.172.2.6"
    environment:
      METRICS_INTERVAL: 600
      GRAPH_HOST: metrics
    volumes:
      - "overview_data:/app/html"